name: palavreando
description: Um jogo infantil feito pelos alunos do Instituto Federal de Educação, Ciência e Tecnologia de São Paulo em parceria com os alunos da UNIFAE.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.0.0
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1
  path_provider: ^2.0.11
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/palavreando_logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Developer Images
    - lib/assets/images/developers/henrique.jpeg
    - lib/assets/images/developers/silvia.jpeg
    - lib/assets/images/developers/bia.jpeg
    - lib/assets/images/developers/rafael.jpeg
    - lib/assets/images/developers/marina.jpeg
    - lib/assets/images/developers/naiara.jpeg
    # Image characters
    - lib/assets/images/characterSelect/girl/Menina1.png
    - lib/assets/images/characterSelect/girl/Menina2.png
    - lib/assets/images/characterSelect/girl/Menina3.png
    - lib/assets/images/characterSelect/girl/Menina4.png
    - lib/assets/images/characterSelect/boy/Menino1.png
    - lib/assets/images/characterSelect/boy/Menino2.png
    - lib/assets/images/characterSelect/boy/Menino3.png
    - lib/assets/images/characterSelect/boy/Menino4.png
    # Image tips assets
    - lib/assets/images/tips/banana.png
    # Words assets
    - lib/assets/words/aviao.json
    - lib/assets/words/banana.json
    - lib/assets/words/boneca.json
    - lib/assets/words/cachorro.json
    - lib/assets/words/casa.json
    - lib/assets/words/galinha.json
    - lib/assets/words/gato.json
    - lib/assets/words/lapis.json
    - lib/assets/words/lua.json
    - lib/assets/words/professora.json
