name: palavreando
description: Um jogo infantil feito pelos alunos do Instituto Federal de Educação, Ciência e Tecnologia de São Paulo em parceria com os alunos da UNIFAE.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.0.0
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1
  flutter_screenutil: ^5.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Developer Images
    - lib/assets/images/developers/henrique.jpeg
    - lib/assets/images/developers/silvia.jpeg
    - lib/assets/images/developers/bia.jpeg
    - lib/assets/images/developers/rafael.jpeg
    - lib/assets/images/developers/marina.jpeg
    - lib/assets/images/developers/naiara.jpeg
    # Image characters
    - lib/assets/images/characterSelect/girl/Menina1.png
    - lib/assets/images/characterSelect/girl/Menina2.png
    - lib/assets/images/characterSelect/girl/Menina3.png
    - lib/assets/images/characterSelect/girl/Menina4.png
    - lib/assets/images/characterSelect/boy/Menino1.png
    - lib/assets/images/characterSelect/boy/Menino2.png
    - lib/assets/images/characterSelect/boy/Menino3.png
    - lib/assets/images/characterSelect/boy/Menino4.png
    # Image tips assets
    - lib/assets/images/tips/aviao.png
    - lib/assets/images/tips/banana.png
    - lib/assets/images/tips/boneca.png
    - lib/assets/images/tips/cachorro.png
    - lib/assets/images/tips/casa.png
    - lib/assets/images/tips/galinha.png
    - lib/assets/images/tips/gato.png
    - lib/assets/images/tips/lapis.png
    - lib/assets/images/tips/lua.png
    - lib/assets/images/tips/professora.png
    # Words assets
    - lib/assets/words/aviao.json
    - lib/assets/words/banana.json
    - lib/assets/words/boneca.json
    - lib/assets/words/cachorro.json
    - lib/assets/words/casa.json
    - lib/assets/words/galinha.json
    - lib/assets/words/gato.json
    - lib/assets/words/lapis.json
    - lib/assets/words/lua.json
    - lib/assets/words/professora.json
    # Image Character FullBody
    # Image Girl
    - lib/assets/images/character/girl/meninaCabeloLoiroForca.png
    - lib/assets/images/character/girl/meninaCabeloMarromForca.png
    - lib/assets/images/character/girl/meninaCabeloPretoForca.png
    - lib/assets/images/character/girl/meninaCabeloRuivoForca.png
    # Image Boy
    - lib/assets/images/character/boy/meninoCabeloLoiroForca.png
    - lib/assets/images/character/boy/meninoCabeloMarromForca.png
    - lib/assets/images/character/boy/meninoCabeloPretoForca.png
    - lib/assets/images/character/boy/meninoCabeloRuivoForca.png
    # Image Girl Crying
    - lib/assets/images/character/girl/cry/MeninaCabeloLoiroChorando.png
    - lib/assets/images/character/girl/cry/MeninaCabeloMarromChorando.png
    - lib/assets/images/character/girl/cry/MeninaCabeloPretoChorando.png
    - lib/assets/images/character/girl/cry/MeninaCabeloRuivoChorando.png
    # Image Boy Crying
    - lib/assets/images/character/boy/cry/MeninoCabeloLoiroChorando.png
    - lib/assets/images/character/boy/cry/MeninoCabeloMarromChorando.png
    - lib/assets/images/character/boy/cry/MeninoCabeloPretoChorando.png
    - lib/assets/images/character/boy/cry/MeninoCabeloRuivoChorando.png
    # Images
    - lib/assets/images/home.png
    - lib/assets/images/tornera.png
    - lib/assets/images/telaAcertou.png
    # Gotas
    - lib/assets/images/gotas/gotaMenor.png
    - lib/assets/images/gotas/gota2.png
    - lib/assets/images/gotas/gota3.png
    - lib/assets/images/gotas/gota4.png
    - lib/assets/images/gotas/gota5.png
    - lib/assets/images/gotas/gota6.png
