name: palavreando
description: Um jogo infantil feito pelos alunos do Instituto Federal de Educação, Ciência e Tecnologia de São Paulo em parceria com os alunos da UNIFAE.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.0.0
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
